/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherApiForVizrt) {
      root.WeatherApiForVizrt = {};
    }
    root.WeatherApiForVizrt.Change = factory(root.WeatherApiForVizrt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Change model module.
   * @module model/Change
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Change</code>.
   * @alias module:model/Change
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Change</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Change} obj Optional instance to populate.
   * @return {module:model/Change} The populated <code>Change</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('change1hr')) {
        obj['change1hr'] = ApiClient.convertToType(data['change1hr'], 'Number');
      }
      if (data.hasOwnProperty('change3hr')) {
        obj['change3hr'] = ApiClient.convertToType(data['change3hr'], 'Number');
      }
      if (data.hasOwnProperty('change6hr')) {
        obj['change6hr'] = ApiClient.convertToType(data['change6hr'], 'Number');
      }
      if (data.hasOwnProperty('change12hr')) {
        obj['change12hr'] = ApiClient.convertToType(data['change12hr'], 'Number');
      }
      if (data.hasOwnProperty('change24hr')) {
        obj['change24hr'] = ApiClient.convertToType(data['change24hr'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} change1hr
   */
  exports.prototype['change1hr'] = undefined;
  /**
   * @member {Number} change3hr
   */
  exports.prototype['change3hr'] = undefined;
  /**
   * @member {Number} change6hr
   */
  exports.prototype['change6hr'] = undefined;
  /**
   * @member {Number} change12hr
   */
  exports.prototype['change12hr'] = undefined;
  /**
   * @member {Number} change24hr
   */
  exports.prototype['change24hr'] = undefined;



  return exports;
}));


