/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CumulativePressure', 'model/CumulativeRain', 'model/CumulativeSnow', 'model/CumulativeTemperature'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CumulativePressure'), require('./CumulativeRain'), require('./CumulativeSnow'), require('./CumulativeTemperature'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherApiForVizrt) {
      root.WeatherApiForVizrt = {};
    }
    root.WeatherApiForVizrt.Cumulative = factory(root.WeatherApiForVizrt.ApiClient, root.WeatherApiForVizrt.CumulativePressure, root.WeatherApiForVizrt.CumulativeRain, root.WeatherApiForVizrt.CumulativeSnow, root.WeatherApiForVizrt.CumulativeTemperature);
  }
}(this, function(ApiClient, CumulativePressure, CumulativeRain, CumulativeSnow, CumulativeTemperature) {
  'use strict';




  /**
   * The Cumulative model module.
   * @module model/Cumulative
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Cumulative</code>.
   * @alias module:model/Cumulative
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Cumulative</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Cumulative} obj Optional instance to populate.
   * @return {module:model/Cumulative} The populated <code>Cumulative</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('temperature')) {
        obj['temperature'] = CumulativeTemperature.constructFromObject(data['temperature']);
      }
      if (data.hasOwnProperty('rain')) {
        obj['rain'] = CumulativeRain.constructFromObject(data['rain']);
      }
      if (data.hasOwnProperty('snow')) {
        obj['snow'] = CumulativeSnow.constructFromObject(data['snow']);
      }
      if (data.hasOwnProperty('pressure')) {
        obj['pressure'] = CumulativePressure.constructFromObject(data['pressure']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CumulativeTemperature} temperature
   */
  exports.prototype['temperature'] = undefined;
  /**
   * @member {module:model/CumulativeRain} rain
   */
  exports.prototype['rain'] = undefined;
  /**
   * @member {module:model/CumulativeSnow} snow
   */
  exports.prototype['snow'] = undefined;
  /**
   * @member {module:model/CumulativePressure} pressure
   */
  exports.prototype['pressure'] = undefined;



  return exports;
}));


