/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Conditions', 'model/Location', 'model/Stats'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Conditions'), require('./Location'), require('./Stats'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherApiForVizrt) {
      root.WeatherApiForVizrt = {};
    }
    root.WeatherApiForVizrt.PointData = factory(root.WeatherApiForVizrt.ApiClient, root.WeatherApiForVizrt.Conditions, root.WeatherApiForVizrt.Location, root.WeatherApiForVizrt.Stats);
  }
}(this, function(ApiClient, Conditions, Location, Stats) {
  'use strict';




  /**
   * The PointData model module.
   * @module model/PointData
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>PointData</code>.
   * @alias module:model/PointData
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PointData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PointData} obj Optional instance to populate.
   * @return {module:model/PointData} The populated <code>PointData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('lastUpdated')) {
        obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = Location.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('conditions')) {
        obj['conditions'] = Conditions.constructFromObject(data['conditions']);
      }
      if (data.hasOwnProperty('stats')) {
        obj['stats'] = Stats.constructFromObject(data['stats']);
      }
    }
    return obj;
  }

  /**
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Date} lastUpdated
   */
  exports.prototype['lastUpdated'] = undefined;
  /**
   * @member {module:model/Location} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {module:model/Conditions} conditions
   */
  exports.prototype['conditions'] = undefined;
  /**
   * @member {module:model/Stats} stats
   */
  exports.prototype['stats'] = undefined;



  return exports;
}));


