/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherApiForVizrt) {
      root.WeatherApiForVizrt = {};
    }
    root.WeatherApiForVizrt.Total = factory(root.WeatherApiForVizrt.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Total model module.
   * @module model/Total
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Total</code>.
   * @alias module:model/Total
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Total</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Total} obj Optional instance to populate.
   * @return {module:model/Total} The populated <code>Total</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total1hr')) {
        obj['total1hr'] = ApiClient.convertToType(data['total1hr'], 'Number');
      }
      if (data.hasOwnProperty('total3hr')) {
        obj['total3hr'] = ApiClient.convertToType(data['total3hr'], 'Number');
      }
      if (data.hasOwnProperty('total6hr')) {
        obj['total6hr'] = ApiClient.convertToType(data['total6hr'], 'Number');
      }
      if (data.hasOwnProperty('total12hr')) {
        obj['total12hr'] = ApiClient.convertToType(data['total12hr'], 'Number');
      }
      if (data.hasOwnProperty('total24hr')) {
        obj['total24hr'] = ApiClient.convertToType(data['total24hr'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} total1hr
   */
  exports.prototype['total1hr'] = undefined;
  /**
   * @member {Number} total3hr
   */
  exports.prototype['total3hr'] = undefined;
  /**
   * @member {Number} total6hr
   */
  exports.prototype['total6hr'] = undefined;
  /**
   * @member {Number} total12hr
   */
  exports.prototype['total12hr'] = undefined;
  /**
   * @member {Number} total24hr
   */
  exports.prototype['total24hr'] = undefined;



  return exports;
}));


