/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeatherApiForVizrt);
  }
}(this, function(expect, WeatherApiForVizrt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeatherApiForVizrt.Conditions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Conditions', function() {
    it('should create an instance of Conditions', function() {
      // uncomment below and update the code to test Conditions
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be.a(WeatherApiForVizrt.Conditions);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property descriptionShort (base name: "descriptionShort")', function() {
      // uncomment below and update the code to test the property descriptionShort
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property cloudCover (base name: "cloudCover")', function() {
      // uncomment below and update the code to test the property cloudCover
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property uvIndex (base name: "uvIndex")', function() {
      // uncomment below and update the code to test the property uvIndex
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property airQuality (base name: "airQuality")', function() {
      // uncomment below and update the code to test the property airQuality
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property rain (base name: "rain")', function() {
      // uncomment below and update the code to test the property rain
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property snow (base name: "snow")', function() {
      // uncomment below and update the code to test the property snow
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property ice (base name: "ice")', function() {
      // uncomment below and update the code to test the property ice
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property temperature (base name: "temperature")', function() {
      // uncomment below and update the code to test the property temperature
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property pressure (base name: "pressure")', function() {
      // uncomment below and update the code to test the property pressure
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property humidity (base name: "humidity")', function() {
      // uncomment below and update the code to test the property humidity
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property wind (base name: "wind")', function() {
      // uncomment below and update the code to test the property wind
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

    it('should have the property sunMoon (base name: "sunMoon")', function() {
      // uncomment below and update the code to test the property sunMoon
      //var instane = new WeatherApiForVizrt.Conditions();
      //expect(instance).to.be();
    });

  });

}));
