/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeatherApiForVizrt);
  }
}(this, function(expect, WeatherApiForVizrt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeatherApiForVizrt.SunMoon();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SunMoon', function() {
    it('should create an instance of SunMoon', function() {
      // uncomment below and update the code to test SunMoon
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be.a(WeatherApiForVizrt.SunMoon);
    });

    it('should have the property sunrise (base name: "sunrise")', function() {
      // uncomment below and update the code to test the property sunrise
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be();
    });

    it('should have the property sunset (base name: "sunset")', function() {
      // uncomment below and update the code to test the property sunset
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be();
    });

    it('should have the property moonrise (base name: "moonrise")', function() {
      // uncomment below and update the code to test the property moonrise
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be();
    });

    it('should have the property moonset (base name: "moonset")', function() {
      // uncomment below and update the code to test the property moonset
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be();
    });

    it('should have the property moonPhase (base name: "moonPhase")', function() {
      // uncomment below and update the code to test the property moonPhase
      //var instane = new WeatherApiForVizrt.SunMoon();
      //expect(instance).to.be();
    });

  });

}));
