/**
 * Weather API for Vizrt
 * This is a Weather API to provide Weather Data to a Vizrt Graphics System
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeatherApiForVizrt);
  }
}(this, function(expect, WeatherApiForVizrt) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeatherApiForVizrt.Temperature();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Temperature', function() {
    it('should create an instance of Temperature', function() {
      // uncomment below and update the code to test Temperature
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be.a(WeatherApiForVizrt.Temperature);
    });

    it('should have the property current (base name: "current")', function() {
      // uncomment below and update the code to test the property current
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property feelsLike (base name: "feelsLike")', function() {
      // uncomment below and update the code to test the property feelsLike
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property windChill (base name: "windChill")', function() {
      // uncomment below and update the code to test the property windChill
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property dewPoint (base name: "dewPoint")', function() {
      // uncomment below and update the code to test the property dewPoint
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property heatIndex (base name: "heatIndex")', function() {
      // uncomment below and update the code to test the property heatIndex
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property max24hr (base name: "max24hr")', function() {
      // uncomment below and update the code to test the property max24hr
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

    it('should have the property min24hr (base name: "min24hr")', function() {
      // uncomment below and update the code to test the property min24hr
      //var instane = new WeatherApiForVizrt.Temperature();
      //expect(instance).to.be();
    });

  });

}));
